
services:
  master1:
    image: hadoop_cluster4:latest
    container_name: master1
    hostname: hadoopmaster
    ports:
      - "9871:9870"
      - "8188:8088"
      - "9000:9000"
    networks:
      - hadoop-net
    environment:
      - ZK_ID=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hadoopmaster:9870"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g

  master2:
    image: hadoop_cluster4:latest
    container_name: master2
    hostname: hadoopmaster1
    ports:
      - "9872:9870"
      - "8288:8088"
    networks:
      - hadoop-net
    environment:
      - ZK_ID=2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hadoopmaster1:9870"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - master1
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g

  master3:
    image: hadoop_cluster4:latest
    container_name: master3
    hostname: hadoopmaster2
    ports:
      - "9873:9870"
      - "8388:8088"
    networks:
      - hadoop-net
    environment:
      - ZK_ID=3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hadoopmaster2:9870"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - master2
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g

  slave1:
    image: hadoop_cluster4:latest
    container_name: slave1
    hostname: hadoopslave
    networks:
      - hadoop-net
    depends_on:
      - master3
    command: tail -f /dev/null
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g

  hbase-master1:
    image: hbase-cl1
    container_name: hbase-master1
    hostname: hbase-master1
    networks:
      - hadoop-net
    environment:
      - HBASE_ROLE=master
      - ZOOKEEPER_QUORUM=hadoopmaster,hadoopmaster1,hadoopmaster2
      - HBASE_ZNODE_PARENT=/hbase
    depends_on:
      - master1
      - master2
      - master3
      - slave1
    ports:
      - "16010:16010"
      - "16000:16000"
    volumes:
      - hbase-logs:/var/log/hbase
      - hbase-data:/hbase/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g

  hbase-master2:
    image: hbase-cl1
    container_name: hbase-master2
    hostname: hbase-master2
    networks:
      - hadoop-net
    environment:
      - HBASE_ROLE=master
      - ZOOKEEPER_QUORUM=hadoopmaster,hadoopmaster1,hadoopmaster2
      - HBASE_ZNODE_PARENT=/hbase
    depends_on:
      - master1
      - master2
      - master3
      - slave1
    ports:
      - "16011:16010"
      - "16001:16000" 
    volumes:
      - hbase-logs:/var/log/hbase
      - hbase-data:/hbase/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g

  regionserver1:
    image: hbase-cl1
    container_name: regionserver1
    hostname: regionserver1
    networks:
      - hadoop-net
    environment:
      - HBASE_ROLE=regionserver
      - ZOOKEEPER_QUORUM=hadoopmaster,hadoopmaster1,hadoopmaster2
      - HBASE_ZNODE_PARENT=/hbase
    depends_on:
      - master1
      - master2
      - master3
      - slave1
    ports:
      - "16020:16020"
      - "16030:16030"
    volumes:
      - hbase-logs:/var/log/hbase
      - hbase-data:/hbase/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g

  regionserver2:
    image: hbase-cl1
    container_name: regionserver2
    hostname: regionserver2
    networks:
      - hadoop-net
    environment:
      - HBASE_ROLE=regionserver
      - ZOOKEEPER_QUORUM=hadoopmaster,hadoopmaster1,hadoopmaster2
      - HBASE_ZNODE_PARENT=/hbase
    depends_on:
      - master1
      - master2
      - master3
      - slave1

    ports:
      - "16021:16021"
      - "16031:16030"
    volumes:
      - hbase-logs:/var/log/hbase
      - hbase-data:/hbase/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2g

networks:
  hadoop-net:
    driver: bridge

volumes:
  hbase-logs:
    driver: local
  hbase-data:
    driver: local